// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JCd6q_5ntkhmaC5jSyFfUS9b93brOzU',
    appId: '1:273356068882:web:89424b61888a7f932d20cb',
    messagingSenderId: '273356068882',
    projectId: 'cleanservice-2ee41',
    authDomain: 'cleanservice-2ee41.firebaseapp.com',
    storageBucket: 'cleanservice-2ee41.firebasestorage.app',
    measurementId: 'G-7R6315T07J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dkxGn0GZR2QFBbARJZnmpDKXQNellB4',
    appId: '1:273356068882:android:aa39ba7f206438532d20cb',
    messagingSenderId: '273356068882',
    projectId: 'cleanservice-2ee41',
    storageBucket: 'cleanservice-2ee41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq9FoPMAXWuP8aaLs04X4Cz_V_jvUg8mM',
    appId: '1:273356068882:ios:96e9796deddbfbd62d20cb',
    messagingSenderId: '273356068882',
    projectId: 'cleanservice-2ee41',
    storageBucket: 'cleanservice-2ee41.firebasestorage.app',
    iosBundleId: 'com.example.modul2cs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq9FoPMAXWuP8aaLs04X4Cz_V_jvUg8mM',
    appId: '1:273356068882:ios:96e9796deddbfbd62d20cb',
    messagingSenderId: '273356068882',
    projectId: 'cleanservice-2ee41',
    storageBucket: 'cleanservice-2ee41.firebasestorage.app',
    iosBundleId: 'com.example.modul2cs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8JCd6q_5ntkhmaC5jSyFfUS9b93brOzU',
    appId: '1:273356068882:web:dcb308d65c011a0f2d20cb',
    messagingSenderId: '273356068882',
    projectId: 'cleanservice-2ee41',
    authDomain: 'cleanservice-2ee41.firebaseapp.com',
    storageBucket: 'cleanservice-2ee41.firebasestorage.app',
    measurementId: 'G-5H3K1LZ9MV',
  );

}